project:
  type: default
  output-dir: docs
  
toc: true

execute:
  echo: false

format:
  html:
    page-layout: full
    self-contained: true
metadata:
  author:
    - "Dawid Żak"
    - "Szymon Hołysz"
  date: "today"